# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: S.Visualz
email: sionk97@hotmail.com
facebook-url: https://www.facebook.com/s.visualz
instagram-url: https://www.instagram.com/s.visualz
description:
  Personal photography website of Sion Kim.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://svisualz.com" # the base hostname & protocol for your site, e.g. http://example.com

gallery-dir: /images/photoswipe/


# Build settings
markdown: kramdown
theme:
plugins:
  - "jekyll-sitemap"
 

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
  
# minifier settings
compress_html:
  clippings: []
  comments: ["<!-- ", " -->"]
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []